// Banco de preguntas — tier 1: ligeras/curiosas, tier 2: personales/profundas, tier 3: coqueteo (sin contenido explícito)
const QUESTIONS = [
// TIER 1 - ligeras
{t:1,q:"¿Cuál es tu plan perfecto para un domingo?"},
{t:1,q:"¿Qué serie no puedes dejar de recomendar?"},
{t:1,q:"¿Playa o montaña?"},
{t:1,q:"¿Cuál es tu comida favorita de todos los tiempos?"},
{t:1,q:"¿Qué canción no puede faltar en tu playlist?"},
{t:1,q:"¿Café o té?"},
{t:1,q:"¿Cuál es tu emoji más usado?"},
{t:1,q:"¿Madrugador o trasnochador?"},
{t:1,q:"¿Cuál fue la última serie que viste completa?"},
{t:1,q:"¿Perro o gato?"},
{t:1,q:"¿Qué app tienes más abierta en el celular?"},
{t:1,q:"¿Cuál es tu postre favorito?"},
{t:1,q:"¿Qué color te representa?"},
{t:1,q:"¿Cuál es tu estación del año favorita?"},
{t:1,q:"¿Prefieres plan en casa o salir?"},
{t:1,q:"¿Cuál fue el último concierto o evento al que fuiste?"},
{t:1,q:"¿Qué es algo que te haga reír sin falta?"},
{t:1,q:"¿Cuál es tu día de la semana favorito?"},
{t:1,q:"¿Cocinas? ¿Cuál es tu plato estrella?"},
{t:1,q:"¿Qué desayunas normalmente?"},
{t:1,q:"¿Cuál es tu película para ver mil veces?"},
{t:1,q:"¿Prefieres mensaje de voz o de texto?"},
{t:1,q:"¿Cuál es tu red social favorita?"},
{t:1,q:"¿Qué haces para desconectar después de un día pesado?"},
{t:1,q:"¿Cuál ha sido tu mejor viaje?"},
{t:1,q:"¿Un lugar al que sueñas viajar?"},
{t:1,q:"¿Cuál es tu snack favorito?"},
{t:1,q:"¿Qué música pones cuando estás de buen humor?"},
{t:1,q:"¿Cuál fue tu primer trabajo?"},
{t:1,q:"¿Qué idioma te gustaría hablar?"},
{t:1,q:"¿Cuál es tu deporte favorito para ver o jugar?"},
{t:1,q:"¿Qué app de música usas?"},
{t:1,q:"¿Cuál es tu hobby de toda la vida?"},
{t:1,q:"¿Prefieres cine o Netflix en casa?"},
{t:1,q:"¿Cuál es tu olor favorito?"},
{t:1,q:"¿Qué comida no soportas?"},
{t:1,q:"¿Cuál fue tu disfraz favorito de niño?"},
{t:1,q:"¿Qué es lo primero que haces al despertar?"},
{t:1,q:"¿Cuál es tu restaurante favorito?"},
{t:1,q:"¿Prefieres desayuno dulce o salado?"},
{t:1,q:"¿Cuál es tu app para pedir comida favorita?"},
{t:1,q:"¿Qué te gustaría aprender este año?"},
{t:1,q:"¿Cuál es tu recuerdo más random de la semana?"},
{t:1,q:"¿Prefieres regalos o experiencias?"},
{t:1,q:"¿Cuál es tu palabra favorita?"},
{t:1,q:"¿Qué serie estás viendo ahora mismo?"},
{t:1,q:"¿Cuál es tu excusa favorita para cancelar planes?"},
{t:1,q:"¿Qué es lo más random que tienes guardado en el celular?"},
{t:1,q:"¿Cuál es tu forma ideal de pasar una tarde lluviosa?"},
{t:1,q:"¿Qué videojuego jugaste más de niño?"},
{t:1,q:"¿Cuál es tu meme favorito de este año?"},
{t:1,q:"¿Qué canción te hace bailar sí o sí?"},
{t:1,q:"¿Cuál es tu ciudad favorita en la que has estado?"},
{t:1,q:"¿Qué es lo que siempre pides cuando sales a comer?"},
{t:1,q:"¿Cuál es tu forma de relajarte un fin de semana?"},
{t:1,q:"¿Qué app usas más para trabajar o estudiar?"},
{t:1,q:"¿Cuál es tu recuerdo de la última Navidad?"},
{t:1,q:"¿Qué es lo que más te gusta de Madrid?"},
{t:1,q:"¿Cuál es tu manía más rara?"},
{t:1,q:"¿Qué serie de dibujos veías de niño?"},
// TIER 2 - personales/profundas
{t:2,q:"¿Qué es algo que la gente se sorprende al saber de ti?"},
{t:2,q:"¿Cuál ha sido tu mayor aprendizaje de una relación pasada?"},
{t:2,q:"¿Qué te hace sentir realmente en confianza con alguien?"},
{t:2,q:"¿Qué es innegociable para ti en una pareja?"},
{t:2,q:"¿Cómo prefieres que te consientan?"},
{t:2,q:"¿Cuál es tu mayor miedo en una relación?"},
{t:2,q:"¿Qué te hace sentir amado/a de verdad?"},
{t:2,q:"¿Cuál ha sido el momento más difícil de tu vida hasta ahora?"},
{t:2,q:"¿Qué es lo que más valoras en una amistad?"},
{t:2,q:"¿Cuál es tu recuerdo más feliz de la infancia?"},
{t:2,q:"¿Qué es algo que quisieras cambiar de ti?"},
{t:2,q:"¿Cuál es tu mayor logro hasta hoy?"},
{t:2,q:"¿Qué es algo que aprendiste de tus padres que quieres repetir?"},
{t:2,q:"¿Qué es algo que aprendiste de tus padres que NO quieres repetir?"},
{t:2,q:"¿Cuál es tu definición de amor?"},
{t:2,q:"¿Qué te da más ansiedad en la vida?"},
{t:2,q:"¿Cuál ha sido tu mayor decepción?"},
{t:2,q:"¿Qué es algo que te gustaría lograr en 5 años?"},
{t:2,q:"¿Cómo describirías tu forma de amar?"},
{t:2,q:"¿Qué es lo que más te cuesta perdonar?"},
{t:2,q:"¿Cuál ha sido tu ruptura más dolorosa y qué aprendiste?"},
{t:2,q:"¿Qué es algo que te hace sentir orgulloso/a de ti mismo/a?"},
{t:2,q:"¿Cómo te gusta que te apoyen cuando tienes un mal día?"},
{t:2,q:"¿Qué es algo de tu pasado que te formó como persona?"},
{t:2,q:"¿Cuál es tu mayor sueño que aún no has cumplido?"},
{t:2,q:"¿Qué es algo que nunca dirías en una primera cita, pero sí ahora?"},
{t:2,q:"¿Cómo sabes que estás con la persona correcta?"},
{t:2,q:"¿Qué es lo que más te ha costado superar?"},
{t:2,q:"¿Cuál es tu forma de mostrar cariño sin decir palabras?"},
{t:2,q:"¿Qué necesitas sentir para abrirte emocionalmente con alguien?"},
{t:2,q:"¿Cuál ha sido la lección más dura que te dio la vida?"},
{t:2,q:"¿Qué es algo que te haría alejarte de alguien para siempre?"},
{t:2,q:"¿Cómo era tu familia cuando eras niño/a?"},
{t:2,q:"¿Qué es lo que más admiras de tus amigos más cercanos?"},
{t:2,q:"¿Cuál es tu mayor inseguridad?"},
{t:2,q:"¿Qué es algo que te gustaría que la gente entendiera de ti?"},
{t:2,q:"¿Cómo manejas los conflictos en una relación?"},
{t:2,q:"¿Qué es lo que más te gusta de estar solo/a?"},
{t:2,q:"¿Cuál ha sido tu mayor acto de valentía?"},
{t:2,q:"¿Qué buscas realmente en este momento de tu vida?"},
{t:2,q:"¿Qué es algo que sueñas hacer antes de los 40?"},
{t:2,q:"¿Cómo prefieres celebrar tus logros?"},
{t:2,q:"¿Qué es lo más importante que te enseñó tu abuela o abuelo?"},
{t:2,q:"¿Cuál ha sido tu decisión más difícil de los últimos años?"},
{t:2,q:"¿Qué necesitas para sentirte en paz contigo mismo/a?"},
{t:2,q:"¿Cómo era tu vida hace 5 años comparada con hoy?"},
{t:2,q:"¿Qué es algo que te hace sentir vivo/a de verdad?"},
{t:2,q:"¿Cuál es tu forma ideal de resolver una pelea?"},
{t:2,q:"¿Qué es algo por lo que estarías dispuesto/a a mudarte de país?"},
{t:2,q:"¿Cómo sabes cuándo confiar en alguien de verdad?"},
{t:2,q:"¿Qué es algo que cambiarías de tu pasado si pudieras?"},
// TIER 3 - coqueteo, tensión (sin contenido explícito)
{t:3,q:"¿Qué fue lo primero que te llamó la atención de mí?"},
{t:3,q:"¿Prefieres que te escriban primero o te gusta dar tú el primer paso?"},
{t:3,q:"¿Cuál crees que sería nuestra primera cita ideal?"},
{t:3,q:"¿Qué tan buena eres coqueteando, del 1 al 10?"},
{t:3,q:"¿Un piropo que nunca te canses de escuchar?"},
{t:3,q:"¿Qué canción pondrías si estuviéramos bailando pegados?"},
{t:3,q:"¿Crees en la química a primera vista?"},
{t:3,q:"¿Qué te parece más atractivo: el humor o la seguridad?"},
{t:3,q:"¿Qué detalle pequeño te enamora más que uno grande?"},
{t:3,q:"¿Cómo te gusta que te conquisten?"},
{t:3,q:"¿Qué es lo más romántico que te han hecho?"},
{t:3,q:"¿Prefieres una cita de aventura o una tranquila con buena conversación?"},
{t:3,q:"¿Qué canción te pondría en modo romántico ahora mismo?"},
{t:3,q:"¿Cuál es tu forma favorita de que te abracen?"},
{t:3,q:"¿Qué tanto te fijas en la mirada de alguien?"},
{t:3,q:"¿Qué es lo que más te atrae de la forma de hablar de alguien?"},
{t:3,q:"¿Prefieres los mensajes con intriga o directos al grano?"},
{t:3,q:"¿Cuál sería tu escenario ideal para un beso de buenas noches?"},
{t:3,q:"¿Qué tan rápido sueles enamorarte?"},
{t:3,q:"¿Qué gesto tuyo crees que enamora sin que te des cuenta?"},
{t:3,q:"¿Prefieres que te digan cosas bonitas o que te las demuestren?"},
{t:3,q:"¿Qué tan importante es para ti la conexión física además de la mental?"},
{t:3,q:"¿Cuál es tu idea de una noche perfecta con alguien especial?"},
{t:3,q:"¿Qué es lo que más se te queda grabado de alguien que te gusta?"},
{t:3,q:"¿Prefieres el misterio o que te lo cuenten todo desde el inicio?"},
{t:3,q:"¿Qué canción describe cómo te sientes hablando conmigo?"},
{t:3,q:"¿Cómo prefieres que alguien te diga que le gustas?"},
{t:3,q:"¿Qué tanto influye el sentido del humor a la hora de gustarte alguien?"},
{t:3,q:"¿Cuál sería un plan tuyo para sorprenderme?"},
{t:3,q:"¿Qué es lo que más disfrutas de una conversación con alguien que te gusta?"}
];
