// Banco de retos — tier 1: divertidos/tiernos, tier 2: personales, tier 3: coqueteo (sin contenido explícito)
const RETOS = [
{t:1,r:"Manda el emoji que mejor describe tu ánimo ahora mismo"},
{t:1,r:"Cuéntale el chisme más random que sepas"},
{t:1,r:"Manda el meme que mejor te representa hoy"},
{t:1,r:"Imita el acento de otro país en un audio"},
{t:1,r:"Describe tu día en solo 3 palabras"},
{t:1,r:"Cuenta un trabalenguas lo más rápido que puedas en un audio"},
{t:1,r:"Manda una foto de dónde estás ahora mismo"},
{t:1,r:"Cuéntale cuál fue tu peor plancha (metida de pata) reciente"},
{t:1,r:"Canta 5 segundos de tu canción favorita en un audio"},
{t:1,r:"Cuéntale tu horóscopo del día tal cual lo leíste"},
{t:1,r:"Manda una foto de tu comida favorita"},
{t:1,r:"Describe con un GIF cómo te sientes hoy"},
{t:1,r:"Cuéntale una anécdota vergonzosa de la escuela"},
{t:1,r:"Manda tu emoji favorito repetido 5 veces"},
{t:1,r:"Cuéntale cuál sería tu nombre artístico si fueras cantante"},
{t:1,r:"Describe tu semana como si fuera el clima"},
{t:1,r:"Cuéntale el último sueño raro que recuerdes"},
{t:1,r:"Manda un audio imitando a un personaje de caricatura"},
{t:1,r:"Cuéntale cuál fue tu última búsqueda en Google"},
{t:1,r:"Describe tu outfit de hoy en un mensaje"},
{t:1,r:"Cuéntale tu comida favorita de la infancia"},
{t:1,r:"Manda la última foto graciosa que tengas guardada"},
{t:1,r:"Cuéntale un dato curioso random que sepas"},
{t:1,r:"Describe a tu mejor amigo/a en 3 palabras"},
{t:1,r:"Cuéntale cuál fue tu primer concierto"},
{t:1,r:"Manda un audio contando un chiste"},
{t:1,r:"Cuéntale tu serie guilty pleasure"},
{t:1,r:"Describe tu ciudad ideal para vivir"},
{t:1,r:"Cuéntale cuál fue tu peor corte de pelo"},
{t:1,r:"Manda 3 emojis que resuman tu personalidad"},
{t:2,r:"Cuéntale un recuerdo feliz de tu infancia"},
{t:2,r:"Escríbele qué fue lo que más te gustó de la conversación de hoy"},
{t:2,r:"Mándale un audio diciendo algo bonito sin pensarlo mucho"},
{t:2,r:"Cuéntale una cualidad tuya de la que te sientes orgulloso/a"},
{t:2,r:"Cuéntale algo que nunca le has dicho a nadie más"},
{t:2,r:"Describe cómo era tu cuarto de adolescente"},
{t:2,r:"Cuéntale un miedo que tengas y por qué"},
{t:2,r:"Cuéntale qué fue lo que más te costó de crecer"},
{t:2,r:"Describe el mejor consejo que te han dado"},
{t:2,r:"Cuéntale algo que te haga sentir vulnerable al compartirlo"},
{t:2,r:"Cuéntale una meta personal que tengas para este año"},
{t:2,r:"Describe cómo te gustaría que te recordaran las personas"},
{t:2,r:"Cuéntale algo que hayas superado y de lo que te sientes orgulloso/a"},
{t:2,r:"Cuéntale qué es lo que más agradeces de tu vida ahora mismo"},
{t:2,r:"Describe un momento en que te sentiste realmente feliz"},
{t:2,r:"Cuéntale una tradición familiar que te guste"},
{t:2,r:"Cuéntale algo que te encantaría que alguien notara de ti"},
{t:2,r:"Describe tu forma ideal de que te cuiden cuando estás enfermo/a"},
{t:2,r:"Cuéntale un momento en que tuviste que ser valiente"},
{t:2,r:"Cuéntale qué es lo que más te gusta de ti mismo/a"},
{t:2,r:"Describe cómo sería un día perfecto para ti de principio a fin"},
{t:2,r:"Cuéntale algo que te dé nostalgia cuando lo piensas"},
{t:2,r:"Cuéntale qué canción te describe como persona ahora mismo"},
{t:2,r:"Describe un momento en que te sentiste muy orgulloso/a de alguien más"},
{t:2,r:"Cuéntale algo que te gustaría cambiar de tu rutina"},
{t:3,r:"Dile qué fue lo primero que pensaste al ver su foto de perfil"},
{t:3,r:"Mándale un audio diciendo su nombre como saludo"},
{t:3,r:"Descríbele el ambiente perfecto para una cita con velas y buena música"},
{t:3,r:"Dile qué canción te recuerda a esa sensación de conexión especial"},
{t:3,r:"Cuéntale cuál sería tu forma ideal de invitarlo/a a salir"},
{t:3,r:"Dile un piropo original, del que no usarías con cualquiera"},
{t:3,r:"Cuéntale qué canción pondrías de fondo si se vieran en persona hoy"},
{t:3,r:"Dile qué fue lo que más te gustó de esta conversación hasta ahora"},
{t:3,r:"Cuéntale cómo te imaginas el momento ideal de despedirse tras una cita"},
{t:3,r:"Mándale un audio diciéndole algo que te gustaría decirle en persona"},
{t:3,r:"Dile qué gesto tuyo crees que le podría gustar sin que lo notes"},
{t:3,r:"Cuéntale cuál sería tu forma de invitarlo/a a bailar"},
{t:3,r:"Descríbele el mejor cumplido que podrías hacerle ahora mismo"},
{t:3,r:"Dile qué canción bailarían juntos en su primera cita"},
{t:3,r:"Cuéntale qué detalle tuyo crees que le llamaría la atención en persona"},
{t:3,r:"Mándale un mensaje como si lo/la estuvieras invitando a una cita ahora"},
{t:3,r:"Dile qué es lo que más ganas te da de conocerlo/a en persona"},
{t:3,r:"Cuéntale cómo te gustaría que fuera el primer abrazo entre ustedes"},
{t:3,r:"Descríbele con 3 palabras la sensación que te genera esta conversación"},
{t:3,r:"Dile cuál sería tu forma ideal de tomarle la mano por primera vez"}
];
